---
- name: "Make sure latest Apache httpd is installed"
  yum: >
     name=httpd
     state=latest
  notify:
        - restart httpd
  tags: httpd_dist

- name: "Make sure httpd is started after reboots"
  service: >
         name=httpd
         enabled=yes
         state=started

  notify:
        - restart httpd
  tags: httpd_dist


- name: "Create download directory if it doesn't exists"
  file: >
      path=${DIST_DIR_ROOT}
      state=directory
      mode=777 
  tags:
      - red5

- name: "Add symlink in document root so mh files can be downloaded via http"
  file: >
         src=
         dest=/var/www/html/downloads 
         state=link
         
  notify:
        - restart httpd
  tags: httpd_dist
