---
- name: installing mysql
  yum: >
       state=latest
       name=$item
  with_items:
             - mysql
             - mysql-server

- name: starting if stopped
  service: >
          name=mysqld
          state=enabled
          state=started
