---
- name: "Remplace /etc/matterhorn/config.properties keys values via ansible template"
  template: >
          src=config_properties.j2
          dest=/opt/matterhorn/etc/matterhorn/config.properties
  notify:
        - restart matterhorn
  tags: config_properties


- name: "Render /etc/matterhorn/matterhorn.conf according to common role vars"
  template: >
             src=matterhorn_conf.j2
             dest=/opt/matterhorn/etc/matterhorn/matterhorn.conf
  notify:
        - restart matterhorn
  tags: matterhorn_conf

- name: "Make sure Matterhorn system user exist"
  user: >
        name=${MATTERHORN_USER}
        state=present
        home=${MATTERHORN_HOME}
        system=yes
  tags: mh_user
  notify:
        - restart matterhorn
  

- name: "Make sure Matterhorn system group exist"
  group: >
        name=${MATTERHORN_GROUP}
        state=present
        system=yes
  tags: mh_group
  notify:
        - restart matterhorn

- name: "Make sure MH system user owns the directories (recursive) specified in the JVM options"
  file: >
        state=directory
        recurse=yes
        owner=${MATTERHORN_USER}
        path=$item
  with_items:
        - ${MATTERHORN_CONF_DIR}
        - ${MATTERHORN_CACHE_DIR}
        - ${MATTERHORN_TEMP_DIR}
        - ${MATTERHORN_LOG_DIR}
  tags: jvm_opt_dirs_owner
  notify:
        - restart matterhorn


- name: "Copy the required $NODE_TYPE.properties in /etc/matterhorn/profiles/"
  copy: >
             src=roles/matterhorn-${MATTERHORN_NODE_TYPE}/files/${MATTERHORN_NODE_TYPE}.properties
             dest=/opt/matterhorn/etc/matterhorn/profiles/
  tags: node_properties
  notify:
        - restart matterhorn
