---
- name: "Install the right repository"
  template: >
          src=entwine_repo.j2
          dest=/etc/yum.repos.d/entwine-mh.repo
          backup=yes
  tags: entwine_repo

- name: "Make sure latest Matterhorn is installed"
  yum: >
     name=entwine-matterhorn
     state=latest
  notify:
        - restart matterhorn
  tags: matterhorn_rpm

- name: "Make sure Apache httpd is installed (used for proxying MH)"
  yum: >
     name=httpd
     state=latest
  notify:
        - restart httpd
  tags: mh_httpd_proxy

- name: "Add httpd to startup levels and start "
  service: >
         name=httpd
         enabled=yes
  tags: mh_httpd_proxy


- name: "Configure httpd for MH proxying via template"
  template: >
          src=httpd_proxy_mh_conf.j2
          dest=/etc/httpd/conf.d/matterhorn.conf
          backup=yes
  notify:
        - restart httpd
  tags: mh_httpd_proxy

- name: "Remplace /etc/matterhorn/config.properties keys values via ansible template"
  template: >
          src=config_properties.j2
          dest=/opt/matterhorn/etc/config.properties
          backup=yes
  notify:
        - restart matterhorn
  tags: config_properties


- name: "Render /etc/matterhorn/matterhorn.conf according to common role vars"
  template: >
             src=matterhorn_conf.j2
             dest=/opt/matterhorn/etc/matterhorn.conf
             backup=yes
  notify:
        - restart matterhorn
  tags: matterhorn_conf

- name: "Make sure Matterhorn system user exist"
  user: >
        name=${MATTERHORN_USER}
        state=present
  tags: mh_user
  notify:
        - restart matterhorn
  

- name: "Make sure Matterhorn system group exist"
  group: >
        name=${MATTERHORN_GROUP}
        state=present
        system=yes
  tags: mh_group
  notify:
        - restart matterhorn

- name: "Make sure MH system user owns the directories (recursive) specified in the JVM options"
  file: >
        state=directory
        recurse=yes
        owner=${MATTERHORN_USER}
        path=$item
  with_items:
        - ${MATTERHORN_CONF_DIR}
        - ${MATTERHORN_CACHE_DIR}
        - ${MATTERHORN_TEMP_DIR}
        - ${MATTERHORN_LOG_DIR}
        #- ${STREAM_DIR}
        #- ${DL_DIR}
        #- ${ARCH_DIR}
        #- ${WFR_DIR}
        #- ${WORK_DIR}
        #- ${org_opencastproject_storage_dir}
  tags: jvm_opt_dirs_owner
  notify:
        - restart matterhorn


- name: "Copy the required $NODE_TYPE.properties in /etc/matterhorn/profiles/"
  copy: >
             src=roles/matterhorn-${MATTERHORN_NODE_TYPE}/files/${MATTERHORN_NODE_TYPE}.properties
             dest=/opt/matterhorn/etc/profiles/
  tags: node_properties
  notify:
        - restart matterhorn
