---
##############################################
###VARIABLES COMMON TO ALL MATTERHORN HOSTS###
##############################################
#
### /etc/matterhorn/matterhorn_conf vars refer to associate template file in 
#roles/common/templates/matterhorn_conf_j2 for comments about each value
PROFILING: OFF

PROFILING_TOOL: newrelic

NEW_RELIC_OPTS: -javaagent:/opt/newrelic/newrelic_jar


MATTERHORN_HOME: /opt/matterhorn

MATTERHORN_CONF_DIR: /opt/matterhorn/etc

FELIX_FILEINSTALL_DIR: /opt/matterhorn/etc/load

MATTERHORN_TEMP_DIR: /var/tmp/matterhorn

MATTERHORN_CACHE_DIR: /var/cache/matterhorn

MATTERHORN_LOG_DIR: /var/log/matterhorn

MATTERHORN_OPTS: -Dmatterhorn_home=/opt/matterhorn

JVM_MEMORY_OPTS: -Xmx2048m -XX:MaxPermSize=256m

JVM_DEBUG_OPTS: -Xdebug -ea:ch -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n

JVM_AWT_OPTS: -Djava_awt.headless=true -Dawt.toolkit=sun.awt.HeadlessToolkit

JVM_ENCODING_OPTS: -Dfile_encoding=utf-8

JVM_MONITORING_OPTS: -Dcom_sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false

#### values for keys in /etc/matterhorn/config_properties associated template is 
#roles/common/templates/config_properties_j2

com_entwine_configuration_review_done: 'true'

org_osgi_service_http_port: '8080'

org_osgi_service_http_secure_enabled: 'false'

org_osgi_service_http_port_secure: '8443'

org_opencastproject_serviceregistry_url: '${org.opencastproject.server.url}/services'

org_opencastproject_jobs_url: '${org.opencastproject.server.url}'

org_opencastproject_storage_dir: /var/matterhorn/local/${ansible_hostname}

org_opencastproject_security_digest_nonce_retries: 12

org_opencastproject_security_digest_nonce_base_time: 300

org_opencastproject_security_digest_nonce_variable_time: 300

org_opencastproject_security_demo_loadusers: false

# SYSTEM REST USER AND ADMIN LOGIN
org_opencastproject_security_digest: matterhorn_system_account
org_opencastproject_security_pass: CHANGE_ME

org_opencastproject_security_admin_user: admin
org_opencastproject_security_admin_pass: opencast
org_opencastproject_security_admin_roles: ROLE_ADMIN,ROLE_USER,ROLE_OAUTH_USER


###DATABASE Setting
org_opencastproject_db_vendor: MySQL

org_opencastproject_db_jdbc_driver: com.mysql.jdbc.Driver

org_opencastproject_db_jdbc_url: jdbc:mysql://${MYSQL_SERVER}/matterhorn

org_opencastproject_db_ddl_generation: false

org_opencastproject_db_ddl_script_generation: false

org_opencastproject_db_jdbc_user: ${MYSQL_USER}

org_opencastproject_db_jdbc_pass: ${MYSQL_PWD}
