---

- name: Copy encoding properties files (iteration by regex wildcard) roles/worker/files/encoding/*.properties to workers in /etc/matterhorn/encoding
  copy: >
      src=$item
      dest=/tmp
  with_fileglob:
      - /home/vagrant/matterhorn-ansible/roles/worker/files/encoding/*.properties

  tags:
       - encod_cp
#- name: Make sure rsync is installed(worker task) 
#  yum: >
#        name=rsync
#        state=latest
#
#- name: Make sure rsync is installed on ansible commander
#  local_action: 


#- name : Synchronize encoding properties directories on workers with the files in roles/worker/files/encoding/ via rsync
#
#  local_action: >
#                command
#                rsync
#                -e 'ssh -o stricthostkeychecking=no -o userknownhostsfile=/dev/null -o batchmode=yes -o passwordauthentication=no' 
#                --delete 
#                -uaSHAXEx 
#                /home/vagrant/matterhorn-ansible/roles/worker/files/encoding/
#                $inventory_hostname:/tmp/encoding
#  tags:
#       - encod_cp
