---

- name: Copy all (iteration by regex wildcard) files in roles/worker/files/encoding to workers in /etc/matterhorn/encoding
  copy: >
      src=$item
      dest=/tmp
  with_fileglob:
      - /home/vagrant/matterhorn-ansible/roles/worker/files/encoding/*
